# Generated by Django 6.0.7 on 2026-08-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('DESCONOCIDO', 'Desconocido')], default='LIBRE', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('sensor_conectado', models.BooleanField(default=True)),
                ('ultimo_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'espacios_estacionamiento',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('programada', 'Programada'), ('espontanea', 'Espontánea')], default='programada', max_length=20)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espacioestacionamiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
